name: Full CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cicd-docker-demo:${{ github.run_number }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd-docker-demo:${{ github.run_number }}

      - name: Deploy to Localhost (Your PC)
        run: |
          # Pull latest image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cicd-docker-demo:${{ github.run_number }}
          
          # Stop and remove old container
          docker stop my-cicd-app || true
          docker rm my-cicd-app || true
          
          # Run new version
          docker run -d --name my-cicd-app -p 8080:80 \
            ${{ secrets.DOCKERHUB_USERNAME }}/cicd-docker-demo:${{ github.run_number }}